theme: jekyll-theme-cayman
title: AP 運算工作室
email: apcomputingstudio@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  提供程式語言學習課程, 技術分享, 交流, 推廣.
baseurl: "/learning" # the subpath of your site, e.g. /blog
url: "https://ponpeinieh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
